language: node_js

node_js:
  - "12"
  - "node"

sudo: false

install:
  - "npm install"
  - "npm install @hapi/hapi@$HAPI_VERSION"

env:
  - HAPI_VERSION="18"
  - HAPI_VERSION="19"

os:
  - "linux"
  - "osx"
  - "windows"
